spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
      max-request-size: 300MB

  influx:
    # 数据库访问路径
    url: http://26.69.0.47:8888
    # 用户名
    user: root
    # 密码
    password: 123456
    # 数据库名称
    database: tzjcdata

  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://26.69.0.47:3306/tzjc?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: rjgs@2016
    # 是否打开sql监控台  (生产环境请务必关闭此选项)
    druid:
      stat-view-servlet:
        enabled: false
#      web-stat-filter:
#        enabled: true
#      filter:
#        config:
#          enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 6
    # Redis服务器地址
    host: 26.69.0.47
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: Xxzx201310-
    # 连接超时时间（毫秒）
    timeout: 5000ms
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  redisson:
    #  单机模式
    host: 26.69.0.47
    port: 6379
    password: 111111
  myconfig:
    # md5的盐
    md5-salt: whatclickme
    # 是否明文存储密码
    is-pw: true
    # 是否彩色SQl日志
    color-sql: true
    # 是否抛出SQL（将sql报错抛出到前端，方便调试，请只在开发环境打开，在生产模式请关闭）
    throw-sql: true
    # 是否把API请求日志输出在控制台
    log-to-file: true
    # 是否把API请求日志记录在数据库
    log-to-db: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# mybatis-plus配置
mybatis-plus:
  # 配置别名包，在mapper.xml中可以直接返回SoMap
  type-aliases-package: com.pj.utils.so
  # 一些配置
  configuration:
    # 控制打印sql
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    # 是否开启下划线转驼峰
    map-underscore-to-camel-case: false
    # 即使属性为null, 也要映射
    call-setters-on-nulls: true
uploadPath:
  C:\dingchi\upload\szywpt\

tzjcweb:
  ip: http://26.69.0.48:9097/warningInfo/sendWarn

emqx:
  ip: 26.69.0.47
  port: 1883
  username: admin
  pwd: rjgs@2016
  clientId: ${random.long}